// Generated by CoffeeScript 1.3.3
(function() {
  var Bat,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Bat = (function(_super) {

    __extends(Bat, _super);

    Bat.speed = 3;

    Bat.prototype.speed = 3;

    Bat.prototype.imgName = "bat";

    Bat.prototype.stoppedFor = 0;

    Bat.stopFor = 500;

    Bat.prototype.stopFor = 500;

    function Bat(world, lane) {
      this.world = world;
      this.lane = lane;
      this.stopAt = Math.floor(Math.random() * this.world.height / 2);
      Bat.__super__.constructor.call(this, this.world, this.lane);
    }

    Bat.prototype.update = function(delta) {
      if (this.y >= this.stopAt && this.stoppedFor < this.stopFor) {
        this.stoppedFor += delta;
        this.stopped = true;
      } else {
        this.stopped = false;
      }
      return Bat.__super__.update.call(this, delta);
    };

    Bat.timeToHit = function() {
      return Bat.__super__.constructor.timeToHit.call(this) + this.stopFor;
    };

    Bat.releaseTime = function() {
      return 10 * 1000;
    };

    Bat.probability = function() {
      return 0.2;
    };

    return Bat;

  })(Enemy);

  window.Bat = Bat;

}).call(this);
