// Generated by CoffeeScript 1.3.3
(function() {
  var ExtraLife,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  ExtraLife = (function(_super) {

    __extends(ExtraLife, _super);

    function ExtraLife() {
      return ExtraLife.__super__.constructor.apply(this, arguments);
    }

    ExtraLife.prototype.speed = 3;

    ExtraLife.prototype.imgFilename = "img/extra_life.png";

    ExtraLife.prototype.onTouchingPlayer = function() {
      this.world.lives += 1;
      return ExtraLife.__super__.onTouchingPlayer.call(this);
    };

    ExtraLife.probability = function() {
      return 0.2;
    };

    return ExtraLife;

  })(FallingThing);

  window.ExtraLife = ExtraLife;

}).call(this);
