// Generated by CoffeeScript 1.3.3
(function() {
  var FallingThing,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FallingThing = (function(_super) {

    __extends(FallingThing, _super);

    FallingThing.y = 10;

    function FallingThing(world) {
      this.world = world;
      FallingThing.__super__.constructor.call(this);
      this.y = 10;
    }

    FallingThing.prototype.update = function(delta) {
      if (!this.stopped) {
        this.centreOn(this.world.middleOfLane(this.lane));
        this.y += delta * this.speed / 6;
      }
      if (!this.touchedPlayer && this.isCollidingWith(this.world.player)) {
        return this.onTouchingPlayer();
      }
    };

    FallingThing.prototype.onTouchingPlayer = function() {
      this.destroy();
      return this.touchedPlayer = true;
    };

    FallingThing.timeToHit = function() {
      var distanceToPlayer;
      distanceToPlayer = World.height - this.y;
      return distanceToPlayer / this.speed;
    };

    FallingThing.releaseTime = function() {
      return 0;
    };

    return FallingThing;

  })(Entity);

  window.FallingThing = FallingThing;

}).call(this);
