// Generated by CoffeeScript 1.3.3
(function() {
  var Goblin,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Goblin = (function(_super) {

    __extends(Goblin, _super);

    function Goblin() {
      return Goblin.__super__.constructor.apply(this, arguments);
    }

    Goblin.speed = 3;

    Goblin.prototype.speed = 3;

    Goblin.prototype.imgName = "goblin";

    return Goblin;

  })(Enemy);

  window.Goblin = Goblin;

}).call(this);
