// Generated by CoffeeScript 1.3.3
(function() {
  var Skeleton,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Skeleton = (function(_super) {

    __extends(Skeleton, _super);

    function Skeleton() {
      return Skeleton.__super__.constructor.apply(this, arguments);
    }

    Skeleton.speed = 2;

    Skeleton.prototype.speed = 2;

    Skeleton.prototype.imgName = "skeleton";

    return Skeleton;

  })(Enemy);

  window.Skeleton = Skeleton;

}).call(this);
