// Generated by CoffeeScript 1.3.3
(function() {
  var Treasure,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Treasure = (function(_super) {

    __extends(Treasure, _super);

    Treasure.speed = 3;

    Treasure.prototype.speed = 3;

    Treasure.prototype.imgName = "treasure";

    function Treasure(world, lane) {
      this.world = world;
      this.lane = lane;
      Treasure.__super__.constructor.call(this, this.world);
    }

    Treasure.prototype.onTouchingPlayer = function() {
      this.world.score += 1;
      return Treasure.__super__.onTouchingPlayer.call(this);
    };

    Treasure.releaseTime = function() {
      return 5 * 1000;
    };

    return Treasure;

  })(FallingThing);

  window.Treasure = Treasure;

}).call(this);
